from __future__ import annotations

from pathlib import Path

from .models import DeclarativeState, DesktopEntry


def _escape_nix(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _quoted_list(items: list[str]) -> str:
    if not items:
        return "[ ]"
    rendered = " ".join(f'"{item}"' for item in items)
    return f"[ {rendered} ]"


def render_nix_module(state: DeclarativeState, entries: dict[str, DesktopEntry]) -> str:
    lines = [
      "# Generated by NixOSmimeAppsUI.",
      "# Edit through the TUI; do not hand-maintain this file unless you also",
      "# accept that the tool may reformat or replace sections later.",
      "{ ... }:",
      "",
      "let",
      "  mimeDefaults = {",
    ]

    for mime_type in sorted(state.mime_defaults):
      lines.append(f'    "{mime_type}" = {_quoted_list(state.mime_defaults[mime_type])};')
    lines.extend([
      "  };",
      "",
      "  mimeRemoved = {",
    ])
    for mime_type in sorted(state.mime_removed):
      lines.append(f'    "{mime_type}" = {_quoted_list(state.mime_removed[mime_type])};')
    lines.extend([
      "  };",
      "",
      "  desktopOverrides = {",
    ])
    for desktop_id in sorted(state.desktop_overrides):
      override = state.desktop_overrides[desktop_id]
      lines.append(f'    "{desktop_id}" = {_quoted_list(override.allowed_mime_types)};')
    lines.extend([
      "  };",
      "in",
      "{",
      "  xdg.mimeApps = {",
      "    enable = true;",
      "    defaultApplications = mimeDefaults;",
      "    associations.removed = mimeRemoved;",
      "  };",
      "",
      "  xdg.configFile.\"mimeapps.list\".force = true;",
      "",
      "  home.file = builtins.listToAttrs (map",
      "    (desktopId:",
      "      let",
      "        original = builtins.getAttr desktopId desktopMetadata;",
      "        allowedMimeTypes = builtins.getAttr desktopId desktopOverrides;",
      "        mimeString = builtins.concatStringsSep \";\" allowedMimeTypes;",
      "      in {",
      "        name = \".local/share/applications/${desktopId}\";",
      "        value.text = ''",
      "          [Desktop Entry]",
      "          Version=1.0",
      "          Type=Application",
      "          Name=${original.name}",
      "          GenericName=${original.genericName}",
      "          Comment=${original.comment}",
      "          Exec=${original.exec}",
      "          Icon=${original.icon}",
      "          Terminal=${if original.terminal then \"true\" else \"false\"}",
      "          Categories=${original.categories}",
      "          StartupNotify=${if original.startupNotify then \"true\" else \"false\"}",
      "          MimeType=${mimeString};",
      "        '';",
      "      })",
      "    (builtins.attrNames desktopOverrides));",
      "}",
      "",
    ])
    if state.desktop_overrides:
        insertion_at = lines.index("  desktopOverrides = {")
        metadata_lines = [
            "  desktopMetadata = {",
        ]
        for desktop_id in sorted(state.desktop_overrides):
            entry = entries[desktop_id]
            metadata_lines.extend([
                f'    "{desktop_id}" = {{',
                f'      name = "{_escape_nix(entry.name)}";',
                '      genericName = "";',
                '      comment = "";',
                f'      exec = "{_escape_nix(entry.exec)}";',
                f'      icon = "{_escape_nix(entry.icon)}";',
                '      terminal = false;',
                '      categories = "Network;Utility;";',
                '      startupNotify = true;',
                "    };",
            ])
        metadata_lines.extend([
            "  };",
            "",
        ])
        lines[insertion_at:insertion_at] = metadata_lines
    return "\n".join(lines)


def write_nix_module(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
