from __future__ import annotations

from pathlib import Path
import re

from .models import DeclarativeState, DesktopEntry


def _escape_nix(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _quoted_list(items: list[str]) -> str:
    if not items:
        return "[ ]"
    rendered = " ".join(f'"{item}"' for item in items)
    return f"[ {rendered} ]"


def _escape_multiline_nix(value: str) -> str:
    return value.replace("''", "'\\''")


def _rewrite_mime_type(original_text: str, mime_types: list[str]) -> str:
    mime_line = f"MimeType={';'.join(mime_types)};"
    pattern = re.compile(r"^MimeType=.*$", re.MULTILINE)
    if pattern.search(original_text):
        return pattern.sub(mime_line, original_text, count=1)
    if not original_text.endswith("\n"):
        return original_text + "\n" + mime_line + "\n"
    return original_text + mime_line + "\n"


def render_nix_module(state: DeclarativeState, entries: dict[str, DesktopEntry]) -> str:
    lines = [
      "# Generated by NixOSmimeAppsUI.",
      "# Edit through the TUI; do not hand-maintain this file unless you also",
      "# accept that the tool may reformat or replace sections later.",
      "{ ... }:",
      "",
      "let",
      "  mimeDefaults = {",
    ]

    for mime_type in sorted(state.mime_defaults):
      lines.append(f'    "{mime_type}" = {_quoted_list(state.mime_defaults[mime_type])};')
    lines.extend([
      "  };",
      "",
      "  mimeAdded = {",
    ])
    for mime_type in sorted(state.mime_added):
      lines.append(f'    "{mime_type}" = {_quoted_list(state.mime_added[mime_type])};')
    lines.extend([
      "  };",
      "",
      "  mimeRemoved = {",
    ])
    for mime_type in sorted(state.mime_removed):
      lines.append(f'    "{mime_type}" = {_quoted_list(state.mime_removed[mime_type])};')
    lines.extend([
      "  };",
      "",
      "  desktopMetadata = {",
    ])
    for desktop_id in sorted(state.desktop_overrides):
      entry = entries[desktop_id]
      rewritten = _rewrite_mime_type(entry.original_text, state.desktop_overrides[desktop_id].allowed_mime_types)
      lines.append(f'    "{desktop_id}" = \'\'')
      lines.extend(f"      {line}" for line in _escape_multiline_nix(rewritten).splitlines())
      if rewritten.endswith("\n"):
        lines.append("    '';\n")
      else:
        lines.append("    '';")
    lines.extend([
      "  };",
      "",
      "  desktopOverrides = {",
    ])
    for desktop_id in sorted(state.desktop_overrides):
      override = state.desktop_overrides[desktop_id]
      lines.append(f'    "{desktop_id}" = {_quoted_list(override.allowed_mime_types)};')
    lines.extend([
      "  };",
      "in",
      "{",
      "  xdg.mimeApps = {",
      "    enable = true;",
      "    defaultApplications = mimeDefaults;",
      "    associations.added = mimeAdded;",
      "    associations.removed = mimeRemoved;",
      "  };",
      "",
      "  xdg.configFile.\"mimeapps.list\".force = true;",
      "",
      "  home.file = builtins.listToAttrs (map",
      "    (desktopId:",
      "      {",
      "        name = \".local/share/applications/${desktopId}\";",
      "        value.text = builtins.getAttr desktopId desktopMetadata;",
      "      })",
      "    (builtins.attrNames desktopOverrides));",
      "}",
      "",
    ])
    return "\n".join(lines)


def write_nix_module(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
